version: '3'
volumes:
  pgdata:
  static_files:
services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=tasksystem.settings.development
      - PYTHONUNBUFFERED=1
    volumes:
      - static_files:/static_files
    ports:
      - 8001:8000
    command: gunicorn -w 4 tasksystem.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: tasksystem
      POSTGRES_DB: tasksystem
      POSTGRES_PASS: tasksystem
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 54326:5432
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80